seed: 42
datapath: "/path/to/dataset/jet-150/"
val_split: 0.1
n_constituents: 32
pt_eta_phi: true
model_class: gnn_uq1

save_path: /tmp/GNN_3_uq1/jet_classifier_large_32
model:
  init_bw_a: 7
  init_bw_k: 7
  k_bw_l1_reg: 1.e-8
  a_bw_l1_reg: 1.e-8
train:
  lr: 0
  bsz: 2790
  epochs: 7000
  cdr_args:
    initial_learning_rate: 3.e-3
    first_decay_steps: 100
    t_mul: 1.0
    m_mul: 1.0
    alpha: 1.e-6
    alpha_steps: 10 # #epoch at lowest lr before next restart. Total cycle = first_decay_steps - alpha_steps
beta:
  intervals:
    - - 0
      - 0.2e-7
      - linear
    - - 2000
      - 3.e-7
      - log
    - - ${train.epochs}
      - 3.e-6
      - constant

